# Generated by Django 3.1.7 on 2021-03-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210309_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='description',
        ),
    ]
